apiVersion: apps/v1
kind: Deployment
metadata:
  name: saga-recommender-api-deployment
  labels:
    app: saga-recommender-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saga-recommender-api
  template:
    metadata:
      labels:
        app: saga-recommender-api
    spec:
      containers:
        - name: saga-recommender-api
          image: {{ .Values.deployment.image }}
          env:
            - name: DB_NAME
              value: {{ .Values.deployment.dbname }}
            - name: DB_USER
              value: {{ .Values.deployment.dbuser }}
            - name: DB_USER_PASS
              value: {{ .Values.deployment.dbuserpass }}
            - name: DB_ENDPOINT
              value: {{ .Values.deployment.dbendpoint }}
          ports:
          - containerPort: {{ .Values.deployment.port }}