apiVersion: batch/v1
kind: Job
metadata:
  labels:
    run: link-parser
  name: link-parser
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - image: 053273560072.dkr.ecr.ap-southeast-2.amazonaws.com/saga-link-parser:latest
          name: link-parser
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-user
            - name: DB_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-user-pass
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-name
            - name: DB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-endpoint
