apiVersion: batch/v1
kind: Job
metadata:
  labels:
    run: new-topics
  name: new-topics
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - image: 053273560072.dkr.ecr.ap-southeast-2.amazonaws.com/saga-new-topics:latest
          name: new-topics
          env:
            - name: TOPIC_FILE_URL
              value: $TOPIC_FILE_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-user
            - name: DB_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-user-pass
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-name
            - name: DB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-endpoint
